Drop Xcode 13.4.1 support
The following errors occur only on Xcode 13.4.1. Addressing them would
significantly impair the usability of this library’s API. Therefore, I have
decided not to support Xcode 13.4.1.

> /.../FloatingPanel/Sources/SwiftUI/FloatingPanelView.swift:9:33: error: protocol 'FloatingPanelCoordinator' can only be used as a generic constraint because it has Self or associated type requirements
>     let coordinator: () -> (any FloatingPanelCoordinator)
>                                 ^
> /.../FloatingPanel/Sources/SwiftUI/FloatingPanelView.swift:78:42: error: protocol 'FloatingPanelCoordinator' can only be used as a generic constraint because it has Self or associated type requirements
>     public func makeCoordinator() -> any FloatingPanelCoordinator {
>                                          ^
> /.../FloatingPanel/Sources/SwiftUI/View+floatingPanel.swift:26:67: error: 'some' types are only implemented for the declared type of properties and subscripts and the return type of functions
>         @ViewBuilder _ content: @escaping (FloatingPanelProxy) -> some View
>                                                                   ^
> /.../FloatingPanel/Sources/SwiftUI/View+floatingPanel.swift:26:9: error: result builder attribute 'ViewBuilder' can only be applied to a parameter of function type
>         @ViewBuilder _ content: @escaping (FloatingPanelProxy) -> some View
>         ^
> /.../FloatingPanel/Sources/SwiftUI/View+floatingPanel.swift:24:31: error: default argument value of type 'FloatingPanelDefaultCoordinator.Type' cannot be converted to type 'T.Type'
>         coordinator: T.Type = FloatingPanelDefaultCoordinator.self,
>                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                                    as! T.Type
> /.../FloatingPanel/Sources/SwiftUI/View+floatingPanel.swift:28:9: error: generic parameter 'ContentView' could not be inferred
>         FloatingPanelView(
>         ^
> /.../FloatingPanel/Sources/SwiftUI/FloatingPanelView.swift:8:49: note: 'ContentView' declared as parameter to type 'FloatingPanelView'
> public struct FloatingPanelView<MainView: View, ContentView: View>: UIViewControllerRepresentable {
>                                                 ^
> /.../FloatingPanel/Sources/SwiftUI/View+floatingPanel.swift:28:9: note: explicitly specify the generic arguments to fix this issue
>         FloatingPanelView(
>         ^
>                          <Self, <#ContentView: View#>>